# Generated by Django 5.1.3 on 2024-11-11 03:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pop_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 11, 3, 35, 9, 955024, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(choices=[('A', 'PYTHON'), ('B', 'DJANGO')]),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(unique_for_date='pop_date', upload_to='images/articles'),
        ),
    ]
