# Generated by Django 5.1.3 on 2024-11-14 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_article_floatfield_article_myfile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='myfile',
            field=models.BinaryField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='article',
            name='pop_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 14, 10, 5, 37, 419758, tzinfo=datetime.timezone.utc)),
        ),
    ]
