# Generated by Django 5.1.3 on 2024-11-14 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_article_pop_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='myfile',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='pop_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 14, 10, 7, 20, 685607, tzinfo=datetime.timezone.utc)),
        ),
    ]
