# Generated by Django 5.1.3 on 2024-11-26 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_alter_article_options_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pop_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 26, 8, 30, 37, 823270, tzinfo=datetime.timezone.utc)),
        ),
    ]
