# Generated by Django 5.1.3 on 2024-11-26 08:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_alter_article_pop_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pop_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 26, 8, 31, 3, 213629, tzinfo=datetime.timezone.utc)),
        ),
    ]
