# Generated by Django 5.1.3 on 2024-11-26 08:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_alter_article_pop_date_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pop_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 26, 8, 35, 31, 359068, tzinfo=datetime.timezone.utc)),
        ),
    ]
