# Generated by Django 5.1.3 on 2024-11-26 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_comment_delete_new_alter_article_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pop_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 26, 18, 38, 21, 403082, tzinfo=datetime.timezone.utc)),
        ),
    ]
