# Generated by Django 5.1.3 on 2024-11-27 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_message_age_message_date_alter_article_pop_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='age',
        ),
        migrations.RemoveField(
            model_name='message',
            name='date',
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='pop_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 27, 15, 55, 22, 375158, tzinfo=datetime.timezone.utc)),
        ),
    ]
