# Generated by Django 5.1.3 on 2024-12-11 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0043_remove_message_age_remove_message_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 11, 6, 53, 16, 297275, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='article',
            name='pop_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 11, 6, 53, 16, 297221, tzinfo=datetime.timezone.utc)),
        ),
    ]
